<div id="wrapper">
    <div id="login" class="animate form">
        <section class="login_content">
            <form autocomplete="off" action="index/login" method="post">
                <h1>User Login</h1>
                <div>
                    <input name ="username" type="text" class="form-control" placeholder="Enter User Name" required="" />
                </div>
                <div>
                    <input name="password" type="password" class="form-control" placeholder="Enter Password" required="" />
                </div>
                <div>

                    <button class="btn btn-success" type="submit" name="login" value="login">Submit</button>
                    <!--              <a class="reset_pass" href="#">Lost your password?</a>-->
                </div>
                <div class="clearfix"></div>
                <div class="separator">

<!--                    <p class="change_link">
                        <a href="#toregister" class="to_register"> Check Ticket Fare </a>
                    </p>-->
                    <div class="clearfix"></div>
                    <br />
                    <div>
                        <br>Technical Support and Maintenance By<br>
                        <a href="http://tonmoysaharoy.ml" target="blink">Tonmoy Saha Roy</a>© 2016 
                    </div>
                </div>
            </form>
            <!-- form -->
        </section>
        <!-- content -->
    </div>

</div>