<table class="table table-striped">
    <tbody>
        <tr>
            <td style="width: 30%">Upload File 1 (PDF Only):</td>
            <td style="width: 50%"><input type="file" accept="application/pdf"  id="fileToUpload1"></td>
            <td style="width: 20%"><?php if ($this->filelist[0]['FILE_NO'] != NULL) { ?>
                <div class="col-sm-12">
                    <a target="blink" href="<?php echo $this->baseUrl() . '/' . $this->filelist[0]['FILE_PATH']; ?>" class="btn btn-sm btn-info" ><b>View File</b></a>
                </div>
                <?php } ?></td>
        </tr>
    </tbody>


</table>


