<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"  style="color:red">Finalize Bill</h4>
            </div>
            <form id="newbillform" class="form-horizontal form-label-left" novalidate autocomplete="off" action="<?= $this->baseUrl() ?>/ajax/finalizebill" method="post">
                <div class="modal-body">
                    <input type="hidden" name="ca_no" value="<?= $this->ca_no; ?>">
                    <input type="hidden" name="p_bill_id" value="<?= $this->bill_id; ?>">

                    <div class="item form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12">Measurement Book(MB) No. <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" name="p_mb_no" value="<?= $this->billInfo['MB_NO']?>" placeholder="Please Enter Measurement Book(MB) No." required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                 
                </div>


                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" name="submit" value="submit" class="btn btn-primary">Finalize Bill</button>
                </div>

            </form>

        </div>
    </div>
</div>





