<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"  style="color:red">Create New Bill</h4>
            </div>
            <form id="newbillform" class="form-horizontal form-label-left" novalidate autocomplete="off" action="<?= $this->baseUrl() ?>/ajax/newbill" method="post">
                <div class="modal-body">
                    <input type="hidden" name="ca_no" value="<?= $this->ca_no; ?>">
                    <input type="hidden" name="p_bill_id" value="<?= $this->bill_id; ?>">

                    <div class="item form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12">Measurement Book(MB) No. <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" name="p_mb_no" value="<?= $this->billInfo['MB_NO']?>" placeholder="Please Enter Measurement Book(MB) No." required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12" for="email">Measurement Book(MB) Page No.<span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" name="p_mb_pg_no" value="<?= $this->billInfo['MB_PG_NO']?>" placeholder="Please Enter Measurement Book(MB) Page No." required="required"  class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12">MB Date <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input id="billdate"  type="text" value="<?= $this->billInfo['MB_DATE']?>"  name="p_date" class="date-picker form-control col-md-7 col-xs-12" placeholder="Enter MB Date" required="required">
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12" for="email">Cheque Page No.<span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" name="p_cheque_no" value="<?= $this->billInfo['CHEQUE_NO']?>" placeholder="Please Enter Cheque No." required="required"  class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="control-label col-md-4 col-sm-4 col-xs-12" for="email">Voucher No.<span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" name="p_voucher_no" value="<?= $this->billInfo['VOUCHER_NO']?>" placeholder="Please Enter Voucher No." required="required"  class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                </div>


                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" name="submit" value="submit" class="btn btn-primary">Create New Bill</button>
                </div>

            </form>

        </div>
    </div>
</div>



<script type="text/javascript">
    $(window).on('shown.bs.modal', function () {
        $('#billdate').daterangepicker({
            singleDatePicker: true,
            calender_style: "picker_2"
        }, function (start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
        })
    });

</script>

