<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel" style="color:red">Release Retention Money</h4>
            </div>
            <form id="form" class="form-horizontal form-label-left" novalidate autocomplete="off" action="<?= $this->baseUrl() ?>/ajax/releaseretention" method="post">
                <div class="modal-body">
                    <input type="hidden" name="p_ca_no" value="<?= $this->ca_no ?>">

                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Work Order Value
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" readonly value="<?= number_format($this->work_value) ?>" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>


                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Net Payable Amount
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" readonly value="<?= number_format($this->net_pay) ?>" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Retention Money
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input id="ret_money" type="text" readonly value="<?= $this->ret_amt ?>" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>


                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Enter Amount <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="number"  onblur="checkvalue(this.value)" name="p_amount" placeholder="Please Enter Retention Amount" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Enter Cheque No. <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" name="p_cheque_no" placeholder="Please Enter Cheque No." required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Enter Voucher No. <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" name="p_voucher_no" placeholder="Please Enter Voucher No." required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Date <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input id="ret_date" name="p_date" class="date-picker form-control col-md-7 col-xs-12" placeholder="Enter Cheque Date"  required="required" type="text">
                        </div>
                    </div>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" name="submit" value="submit" class="btn btn-primary">Release Money</button>
                </div>

            </form>


        </div>
    </div>
</div>


<script type="text/javascript">
    $(window).on('shown.bs.modal', function () {
        $('#ret_date').daterangepicker({
            singleDatePicker: true,
            calender_style: "picker_2"
        }, function (start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
        })
    });


    function checkvalue(amount) {
        var ret = document.getElementById("ret_money").value;
        if (parseInt(ret) != parseInt(amount))
            alert("RETENTION AMOUNT SHOULD BE EQUAL TO RECOMMENDED AMOUNT");
    }

</script>

