<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Upload File</h2>

            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <td style="width: 30%">Upload File 1 (PDF Only):</td>
                        <td style="width: 50%"><input type="file" accept="application/pdf"  id="fileToUpload1"></td>
                        <td style="width: 20%"><?php if ($this->filelist[0]['FILE_NO'] != NULL) { ?>
                            <div class="col-sm-12">
                                <a target="blink" href="<?php echo $this->baseUrl() . '/' . $this->filelist[0]['FILE_PATH']; ?>" class="btn btn-sm btn-info" ><b>View File</b></a>
                            </div>
                            <?php } ?></td>
                    </tr>
                    <tr>
                        <td style="width: 30%">Upload File 2 (PDF Only):</td>
                        <td style="width: 50%"><input type="file" accept="application/pdf"  id="fileToUpload2"></td>
                        <td style="width: 20%"><?php if ($this->filelist[1]['FILE_NO'] != NULL) { ?>
                                <div class="col-sm-12">
                                    <a target="blink" href="<?php echo $this->baseUrl() . '/' . $this->filelist[1]['FILE_PATH']; ?>" class="btn btn-sm btn-info" ><b>View File</b></a>
                                </div>
                            <?php } ?></td>
                    </tr>
                    <tr>
                        <td style="width: 30%">Upload File 3 (PDF Only):</td>
                        <td style="width: 50%"><input type="file" accept="application/pdf"  id="fileToUpload3"></td>
                        <td style="width: 20%"><?php if ($this->filelist[2]['FILE_NO'] != NULL) { ?>
                                <div class="col-sm-12">
                                    <a target="blink" href="<?php echo $this->baseUrl() . '/' . $this->filelist[2]['FILE_PATH']; ?>" class="btn btn-sm btn-info" ><b>View File</b></a>
                                </div>
                            <?php } ?></td>
                    </tr>
                </tbody>


            </table>
            <div class="ln_solid"></div>
            <div class="form-group">
                <div class="col-md-6 col-md-offset-3">
                    <a href="index" class="btn btn-primary">Cancel</a>
                    <button type="submit" id="upload" class="btn btn-success">Submit</button>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    $('#upload').on('click', function () {
        var file_data1 = $('#fileToUpload1').prop('files')[0];
        var file_data2 = $('#fileToUpload2').prop('files')[0];
        var file_data3 = $('#fileToUpload3').prop('files')[0];
        var form_data = new FormData();

        var ca_no = document.getElementById('ca_no').value;
        form_data.append('file1', file_data1);
        form_data.append('file2', file_data2);
        form_data.append('file3', file_data3);
        form_data.append('ca_no', ca_no);
        var link = "<?= $this->baseUrl() ?>/ajax/storefile";
        $.ajax({
            url: link,
            dataType: 'text',
            cache: false,
            contentType: false,
            processData: false,
            data: form_data,
            type: 'post',
            success: function (msg) {
                document.location.reload(); 
            }
        });
    });
</script>