<?php $paymentinfo = $this->paymentinfo; ?>

<div id="mycontainer"  class="row">
    <div class="col-md-12 col-sm-12 col-xs-12" style="padding-top: 20px" >
        <div class="x_panel">
            <div class="x_title">
                <h2>View Contract Agreement</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <form id="form" class="form-horizontal form-label-left" novalidate autocomplete="off">

                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" >Enter CA No. <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input id='ca_no' class="form-control col-md-7 col-xs-12" value="<?= $this->appdata['CA_NO'] ?>" readonly type="text">
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" >Name of Work <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" class="form-control col-md-7 col-xs-12" value="<?= $this->appdata['CA_NAME'] ?>" readonly>
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Select Sector <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" class="form-control col-md-7 col-xs-12" value="<?= $this->appdata['SECTOR_NAME'] ?>" readonly>
                        </div>
                    </div>


                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Select Sub-Division <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" class="form-control col-md-7 col-xs-12" value="<?= $this->appdata['SUB_DIV_NAME'] ?>" readonly>
                        </div>
                    </div>


                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Approved Estimate Cost <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" class="form-control col-md-7 col-xs-12" value="<?= $this->appdata['EST_COST'] ?>" readonly>
                        </div>
                    </div>
                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Cost in Words <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" id="in_words" readonly class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Approving Authority <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" class="form-control col-md-7 col-xs-12" value="<?= $this->appdata['USER_TYPE_NAME'] ?>" readonly>
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Procurement Nature <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" class="form-control col-md-7 col-xs-12" value="<?= $this->appdata['PROC_TYPE_NAME'] ?>" readonly>
                        </div>
                    </div>


                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Procurement Method <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" class="form-control col-md-7 col-xs-12" value="<?= $this->appdata['PROC_METHOD_NAME'] ?>" readonly>
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Work Order Value <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input id="work_value" type="text" class="form-control col-md-7 col-xs-12" value="<?= $this->appdata['WORK_VALUE'] ?>" readonly>
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Value in Words <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" id="in_words_2" readonly class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Select Contractor <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" class="form-control col-md-7 col-xs-12" value="<?= $this->appdata['NAME'] ?>" readonly>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Signing Date <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" class="form-control col-md-7 col-xs-12" value="<?= $this->appdata['SIGN_DATE'] ?>" readonly>
                        </div>
                    </div>
                </form>

            </div>
        </div>


    </div>

    <div class="col-md-12 col-sm-12 col-xs-12" style="padding-top: 20px" >
        <div class="x_panel">
            <div class="x_title">
                <h2>Performance Security Information</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <form class="form-horizontal form-label-left" novalidate autocomplete="off" >

                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Select Payment Method <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input class="form-control col-md-7 col-xs-12" readonly value="<?= $paymentinfo['PAYMENT_METHOD_NAME'] ?>" required="required" type="text">
                        </div>
                    </div>
                    <div class="item form-group">    
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Bank <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input class="form-control col-md-7 col-xs-12" readonly value="<?= $paymentinfo['BANK_NAME'] ?>" required="required" type="text">
                        </div>
                    </div>
                    <div class="item form-group">    
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Branch <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input class="form-control col-md-7 col-xs-12" readonly value="<?= $paymentinfo['BRANCH'] ?>" required="required" type="text">
                        </div>
                    </div>
                    <div class="item form-group">    
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Performance Security No. <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input class="form-control col-md-7 col-xs-12" readonly value="<?= $paymentinfo['PAYORDER_NO'] ?>" required="required" type="text">
                        </div>
                    </div>
                    <div class="item form-group">    
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Date <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input class="form-control col-md-7 col-xs-12" readonly value="<?= $paymentinfo['PAY_DATE'] ?>" required="required" type="text">
                        </div>
                    </div>
                    <div class="item form-group">    
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Amount <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input class="form-control col-md-7 col-xs-12" readonly value="<?= $paymentinfo['AMOUNT'] ?>" required="required" type="text">
                        </div>
                    </div>


                </form>
            </div>
        </div>
    </div>




    <div class="col-md-12 col-sm-12 col-xs-12" style="padding-top: 20px">
        <div class="x_panel">
            <div class="x_title">
                <h2>Payment History [<?= $this->ca_no ?>]</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <?php if ($this->user_type == 2 and $this->appdata['STATUS'] == 'N') { ?><li>
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Make New Payment</button>

                            <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">

                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                                            </button>
                                            <h4 class="modal-title" id="myModalLabel" style="color:red">New Bill Payment</h4>
                                        </div>
                                        <form id="form" class="form-horizontal form-label-left" novalidate autocomplete="off" action="<?= $this->baseUrl() ?>/Staff/billcontractagree" method="post">
                                            <div class="modal-body">
                                                <input type="hidden" name="p_ca_no" value="<?= $this->appdata['CA_NO'] ?>">

                                                <div class="item form-group">
                                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Work Order Value
                                                    </label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                        <input type="text" readonly value="<?= number_format($this->appdata['WORK_VALUE']); ?>" class="form-control col-md-7 col-xs-12">
                                                    </div>
                                                </div>


                                                <div class="item form-group">
                                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Remaining Amount (W.O.)
                                                    </label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                        <input id="due_amt" type="text" readonly value="<?= number_format($this->appdata['WORK_VALUE'] - $this->total_amt); ?>" class="form-control col-md-7 col-xs-12">
                                                    </div>
                                                </div>

                                                <div class="item form-group">
                                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Remaining (%) (W.O.)
                                                    </label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                        <input id="due_prcnt" type="text" readonly value="<?= (($this->appdata['WORK_VALUE'] - $this->total_amt) / $this->appdata['WORK_VALUE']) * 100; ?>" class="form-control col-md-7 col-xs-12">
                                                    </div>
                                                </div>

                                                <div class="item form-group">
                                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Select Running Bill <span class="required">*</span>
                                                    </label>

                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                        <select id="khat" name="p_rn_bill_id" required  onblur="getrestrunningbill(this.value)" class=" form-control">
                                                            <option value="">Please Select</option>
                                                            <?php
                                                            $khatlist = $this->runningBill;
                                                            foreach ($khatlist as $types) {
                                                                ?>
                                                                <option value="<?= $types['RN_BILL_ID'] ?>"><?= $types['SAMOUNT'] ?></option>
                                                            <?php } ?>
                                                        </select>
                                                    </div>
                                                </div>

                                                <div class="item form-group" id="o_remaining_amt" >
                                                </div>

                                                <div class="form-group">
                                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Select a Method <span class="required">*</span></label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                        <select id="method" class="form-control">
                                                            <option value="">Please Select</option>
                                                            <option value="1">Percentage(of remaining running bill)</option>
                                                            <option value="2">Figure</option>
                                                        </select>
                                                    </div>
                                                </div>


                                                <div class="item form-group">
                                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Enter Value <span class="required">*</span>
                                                    </label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                        <input type="number"  onblur="checkvalue(this.value)" placeholder="Please Enter Value" required="required" class="form-control col-md-7 col-xs-12">
                                                    </div>
                                                </div>

                                                <div class="item form-group">
                                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Confirm Bill Amount
                                                    </label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                        <input id="conf_amt" type="text" name="p_amount" readonly  class="form-control col-md-7 col-xs-12">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-primary">Make New Payment</button>
                                            </div>

                                        </form>


                                    </div>
                                </div>
                            </div>
                        </li><?php } ?>
                </ul>
                <div class="clearfix"></div>



            </div>
            <div class="x_content">



                <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                        <tr >
                            <th style="text-align:center">SL#</th>
                            <th style="text-align:center">MB. NO</th>
                            <th style="text-align:center">MB. PAGE NO</th>
                            <th style="text-align:center">DATE</th>
                            <th style="text-align:center" >BILL</th>
                            <th style="text-align:center">AMOUNT</th>
                            
                            <th style="text-align:center" >PERCENTAGE</th>
                            <th style="text-align:center" >RETENTION</th>
                            <th style="text-align:center" >VAT</th>
                            <th style="text-align:center" >IT</th>
                            <th style="text-align:center" >NET PAYABLE</th>
                            <th style="text-align:center" >PAYMENT STATUS</th>
                        </tr>
                    </thead>


                    <tbody>
                        <?php
                        $i = 1;
                        $sum = 0;
                        $sum2 = 0;
                        $ret = 0;
                        $vat = 0;
                        $it = 0;
                        $net = 0;
                        foreach ($this->allpayment as $app) {
                            $ret = $ret + $app['RETENATION'];
                            $vat = $vat + $app['VAT'];
                            $it = $it + $app['IT'];
                            ?>
                            <tr>
                                <td style="text-align:center"><?= $i++; ?></td>
                                <td style="text-align:center"><?= $app['MB_NO'] ?></td>
                                <td style="text-align:center"><?= $app['MB_PG_NO'] ?></td>
                                <td style="text-align:center"><?= $app['MB_DATE'] ?></td>
                                <td style="text-align:center"><?= $app['RN_BILL_NAME'] ?></td>
                                <td style="text-align:right"><?php
                                    $sum2 = $sum2 + $app['AMOUNT'];
                                    echo number_format($app['AMOUNT'])
                                    ?>.৳</td>
                                
                                <td style="text-align:center"><?php
                                    $percnt = ($app['AMOUNT'] / $this->appdata['WORK_VALUE']) * 100;
                                    $sum = $sum + $percnt;
                                    echo number_format($percnt) . "%";
                                    ?></td>
                                <td style="text-align:right"><?= number_format($app['RETENATION']) ?>.৳</td>
                                <td style="text-align:right"><?= number_format($app['VAT']) ?>.৳</td>
                                <td style="text-align:right"><?= number_format($app['IT']) ?>.৳</td>
                                <td style="text-align:right"><?php
                                    $n_amt = $app['AMOUNT'] - $app['RETENATION'] - $app['VAT'] - $app['IT'];
                                    $net = $net + $n_amt;
                                    echo number_format($n_amt)
                                    ?>.৳</td>
                                <td style="text-align:center"><?php if ($app['STATUS'] == 'Y') { ?>
                                        <a style="color:green">PAID</a>
                                    <?php } else {
                                        ?><a style="color:red">UNPAID</a>
                                    <?php }
                                    ?></td>

                            </tr>
                        <?php } ?>
                        <tr>
                            <td style="text-align:right" colspan="5"><b>CUMULATIVE :</b></td>
                            <td style="text-align:right"><b><?= number_format($sum2) ?>.৳</b></td>
                            <td style="text-align:center"><b><?= number_format($sum) . "%" ?></b></td>
                            <td style="text-align:right"><b><?= number_format($ret) . ".৳" ?></b></td>
                            <td style="text-align:right"><b><?= number_format($vat) . ".৳" ?></b></td>
                            <td style="text-align:right"><b><?= number_format($it) . ".৳" ?></b></td>
                            <td style="text-align:right"><b><?= number_format($net) . ".৳" ?></b></td>
                            <td style="text-align:center"></td>

                        </tr>

                        <tr><td style="text-align:right" colspan="5"><b>REMAINING :</b></td>
                            <td style="text-align:right"><b><?= number_format($this->appdata['WORK_VALUE'] - $sum2) ?>.৳</b></td>
                            <td style="text-align:center"><b><?= number_format(100 - $sum) . "%" ?></b></td>
                            <td colspan="5"></td>

                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>


</div>

<script type="text/javascript">

    window.onload = function () {
        number2text(<?= $this->appdata['EST_COST'] ?>);
        number2text2(<?= $this->appdata['WORK_VALUE'] ?>);
    }


    $(document).ready(function () {
        $('#datatable').dataTable();
        $('#datatable-keytable').DataTable({
            keys: true
        });
        $('#datatable-responsive').DataTable();
        $('#datatable-scroller').DataTable({
            ajax: "js/datatables/json/scroller-demo.json",
            deferRender: true,
            scrollY: 380,
            scrollCollapse: true,
            scroller: true
        });
        var table = $('#datatable-fixed-header').DataTable({
            fixedHeader: true
        });
    });
    TableManageButtons.init();


//    $('form').submit(function (e) {
//        e.preventDefault();
//        var submit = true;
//
//        if (!document.getElementById('method').value) {
//            alert('Enter a Method');
//            submit = false;
//            return false;
//        }
//
//        if (!document.getElementById('p_bill_amt').value) {
//            alert('Enter Bill Amount');
//            submit = false;
//            return false;
//        }
//        alert("HI");
//        //submit = checkvalue(document.getElementById('p_bill_amt').value);
//        if (!submit)
//            return false;
//
//        if (submit) {
//            var stat = confirm("Create a Contract Agreement?");
//            if (stat)
//                this.submit();
//        }
//        return false;
//    });


    function getrestrunningbill(bill_id) {
        var link = "<?= $this->baseUrl() ?>/ajax/restrunningbill";
        jQuery.ajax({
            type: "POST",
            url: link,
            data: "bill_id=" + bill_id,
            async: false,
            success: function (msg) {
                jQuery('#o_remaining_amt').html(msg);
            }
        });
    }


    function checkvalue(amt) {
        var submit = true;
        var method = document.getElementById("method").value;
        var total = document.getElementById("remaining_amt").value;
        var due_amt = <?= $this->appdata['WORK_VALUE'] - $this->total_amt ?>;
        var due_prcnt = document.getElementById("due_prcnt").value;
        if (!method)
            alert("Please Select a Method");

        if (method == 1)
        {
//            if (parseInt(amt) <= 5) {
//                alert("WARNING::New Bill Must Be Greater Than 5% of Work Order Value");
//                submit = false;
//            }
            if (parseInt(amt) > parseInt(due_prcnt)) {
                alert("WARNING::New Bill Must Be Less Than Less Than Due Percentage");
                submit = false;
            }

            document.getElementById("conf_amt").value = total * (amt / 100);

        } else {
//            var percent = (amt / total) * 100;
//            if (parseInt(percent) <= 5) {
//                alert("WARNING::New Bill Must Be Greater Than 5% of Work Order Value");
//                submit = false;
//            }
            if (parseInt(amt) > parseInt(due_amt)) {
                alert("WARNING::New Bill Must Be Less Than Less Than Due Amount");
                submit = false;
            }
            document.getElementById("conf_amt").value = amt;
        }
        return submit;
    }

    function number2text(value) {
        var fraction = Math.round(frac(value) * 100);
        var f_text = "";

        if (fraction > 0) {
            f_text = "AND " + convert_number(fraction) + " POYSA";
        }
        document.getElementById("in_words").value = convert_number(value) + " TAKA " + f_text + " ONLY";
    }


    function number2text2(value) {
        var fraction = Math.round(frac(value) * 100);
        var f_text = "";

        if (fraction > 0) {
            f_text = "AND " + convert_number(fraction) + " POYSA";
        }
        document.getElementById("in_words_2").value = convert_number(value) + " TAKA " + f_text + " ONLY";
    }

    function frac(f) {
        return f % 1;
    }

    function convert_number(number)
    {
        if ((number < 0) || (number > 999999999))
        {
            return "NUMBER OUT OF RANGE!";
        }
        var Gn = Math.floor(number / 10000000);  /* Crore */
        number -= Gn * 10000000;
        var kn = Math.floor(number / 100000);     /* lakhs */
        number -= kn * 100000;
        var Hn = Math.floor(number / 1000);      /* thousand */
        number -= Hn * 1000;
        var Dn = Math.floor(number / 100);       /* Tens (deca) */
        number = number % 100;               /* Ones */
        var tn = Math.floor(number / 10);
        var one = Math.floor(number % 10);
        var res = "";

        if (Gn > 0)
        {
            res += (convert_number(Gn) + " KOTI");
        }
        if (kn > 0)
        {
            res += (((res == "") ? "" : " ") +
                    convert_number(kn) + " LAKH");
        }
        if (Hn > 0)
        {
            res += (((res == "") ? "" : " ") +
                    convert_number(Hn) + " THOUSAND");
        }

        if (Dn)
        {
            res += (((res == "") ? "" : " ") +
                    convert_number(Dn) + " HUNDRED");
        }


        var ones = Array("", "ONE", "TWO", "THREE", "FOUR", "FIVE", "SIX", "SEVEN", "EIGHT", "NINE", "TEN", "ELEVEN", "TWELVE", "THIRTEEN", "FOURTEEN", "FIFTEEN", "SIXTEEN", "SEVENTEEN", "EIGHTEEN", "NINETEEN");
        var tens = Array("", "", "TWENTY", "THIRTY", "FOURTY", "FIFTY", "SIXTY", "SEVENTY", "EIGHTY", "NINETY");

        if (tn > 0 || one > 0)
        {
            if (!(res == ""))
            {
                res += " AND ";
            }
            if (tn < 2)
            {
                res += ones[tn * 10 + one];
            }
            else
            {

                res += tens[tn];
                if (one > 0)
                {
                    res += ("-" + ones[one]);
                }
            }
        }

        if (res == "")
        {
            res = "zero";
        }
        return res;
    }


</script>



