<div class="row" id="mycontainer">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">

            <div class="col-md-4 col-sm-4 col-xs-12" style="padding-top: 30px">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>User Information</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>

                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <table class="table table-bordered">
                            <tbody>
                                <tr>
                                    <th scope="row">Full Name</th>
                                    <td><?= $this->userinfo['FULL_NAME'] ?></td>
                                </tr>
                                <tr>
                                    <th scope="row">User Type</th>
                                    <td><?= $this->userinfo['USER_TYPE_NAME'] ?></td>
                                </tr>
                                <tr>
                                    <th scope="row">Email</th>
                                    <td><?= $this->userinfo['EMAIL'] ?></td>
                                </tr>
                                <tr>
                                    <th scope="row">Mobile No.</th>
                                    <td><?= $this->userinfo['MOBILE'] ?></td>
                                </tr>
                                <tr>
                                    <th scope="row">Create Date</th>
                                    <td><?= $this->userinfo['CREATE_DATE'] ?></td>
                                </tr>
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>


            <div class="col-md-8 col-sm-8 col-xs-12" style="padding-top: 30px">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Fund Status</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>

                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <table  class="table table-striped table-bordered">
                            <thead>
                                <tr >
                                    <th >SL#</th>
                                    <th style="text-align:center">Fiscal year</th>

                                    <th style="text-align:right">Approved APP</th>
                                    <th style="text-align:right">Available APP</th>
                                    <th style="text-align:right">Approved DPP</th>
                                    <th style="text-align:right">Available DPP</th>
                                </tr>
                            </thead>


                            <tbody>
                                <?php
                                $i = 1;
                                foreach ($this->fundinfo as $app) {
                                    ?>
                                    <tr <?php if ($app['STATUS'] == 'Y') { ?>style="background-color: lime; color:black "<?php } ?>>
                                        <td style="text-align:center"><?= $i++; ?></td>
                                        <td style="text-align:center"><?= $app['START_YEAR']; ?>-<?= $app['END_YEAR']; ?></td>

                                        <td style="text-align: right"><?= number_format($app['APP_BUDGET']); ?></td>
                                        <td style="text-align: right" <?php if ($app['APP_AVAIL'] < 0) { ?>style="color:red" <?php } ?>><?= number_format($app['APP_AVAIL']); ?></td>
                                        <td style="text-align: right"><?= number_format($app['DPP_BUDGET']); ?></td>
                                        <td style="text-align: right" <?php if ($app['DPP_AVAIL'] < 0) { ?>style="color:red" <?php } ?>><?= number_format($app['DPP_AVAIL']); ?></td>
                                    </tr>
                                <?php } ?>

                            </tbody>
                        </table>

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>



