<div class="row" style="min-height:550px">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">

            <div class="col-md-3 col-sm-3"></div>

            <div class="col-md-6 col-sm-6 col-xs-12" style="padding-top: 30px">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>User Information</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>

                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <table class="table table-bordered">
                            <tbody>
                                <tr>
                                    <th scope="row">Full Name</th>
                                    <td><?= $this->userinfo['FULL_NAME'] ?></td>
                                </tr>
                                <tr>
                                    <th scope="row">User Type</th>
                                    <td><?= $this->userinfo['USER_TYPE_NAME'] ?></td>
                                </tr>
                                <tr>
                                    <th scope="row">Email</th>
                                    <td><?= $this->userinfo['EMAIL'] ?></td>
                                </tr>
                                <tr>
                                    <th scope="row">Mobile No.</th>
                                    <td><?= $this->userinfo['MOBILE'] ?></td>
                                </tr>
                                <tr>
                                    <th scope="row">Create Date</th>
                                    <td><?= $this->userinfo['CREATE_DATE'] ?></td>
                                </tr>
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>



