<div id="mycontainer"  class="row">

    <div class="col-md-12 col-sm-12 col-xs-12" style="padding-top: 20px">
        <div class="x_panel">
            <div class="x_title">
                <h2>Instalment Information</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Create New Instalment</button>

                    <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog modal-lg">
                            <div class="modal-content">

                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                                    </button>
                                    <h4 class="modal-title" id="myModalLabel" style="color:red">Create an Instalment</h4>
                                </div>
                                <form id="form" class="form-horizontal form-label-left" novalidate autocomplete="off" action="<?= $this->baseUrl() ?>/Staff/instalment" method="post">
                                    <div class="modal-body">
                                        <input type="hidden" name="p_instalment_id" value="<?= $this->appdata['CA_NO'] ?>">

                                        <div class="item form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Select Khat <span class="required">*</span>
                                            </label>

                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <select name="p_khat_id" required class="select2_single form-control">
                                                    <option value="">Please Select</option>
                                                    <?php
                                                    $khatlist = $this->helper->GetKhatList();
                                                    foreach ($khatlist as $types) {
                                                        ?>
                                                        <option value="<?= $types['KHAT_ID'] ?>"><?= $types['KHAT_NAME'] ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>


                                        <div class="item form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Select Fiscal Year <span class="required">*</span>
                                            </label>

                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <select name="p_fiscal_id" required class="select2_single form-control">
                                                    <option value="">Please Select</option>
                                                    <?php
                                                    $khatlist = $this->helper->GetFiscalYearList();
                                                    foreach ($khatlist as $types) {
                                                        ?>
                                                        <option value="<?= $types['FISCAL_YR_ID'] ?>"><?= $types['START_YEAR'] ?>-<?= $types['END_YEAR'] ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="item form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" >Approved Amount <span class="required">*</span>
                                            </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input type="number" required name="p_amount" onblur="number2text(this.value)" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>

                                        <div class="item form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Amount in Words <span class="required">*</span>
                                            </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input type="text" id="in_words" readonly class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>


                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Validity Date <span class="required">*</span>
                                            </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input id="birthday"  class="date-picker form-control col-md-7 col-xs-12" placeholder="Enter Validity Date" name="p_valid_date" required="required" type="text">
                                            </div>
                                        </div>


                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                        <button type="submit" class="btn btn-primary">Make Instalment</button>
                                    </div>

                                </form>


                            </div>
                        </div>
                    </div>
                    </li>
                </ul>
                <div class="clearfix"></div>



            </div>
            <div class="x_content">



                <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                        <tr >
                            <th style="text-align:center">SL#</th>
                            <th style="text-align:center">KHAT</th>
                            <th style="text-align:center">FISCAL YEAR</th>
                            <th style="text-align:center">AMOUNT</th>
                            <th style="text-align:center">STATUS</th>
                            <th style="text-align:center" >VALIDITY DATE</th>
                        </tr>
                    </thead>

                    <tbody>

                        <?php
                        $i = 1;
                        foreach ($this->instalmentlist as $app) {
                            ?><tr>
                                <td style="text-align:center"><?= $i++; ?></td>
                                <td style="text-align:center"><?= $app['KHAT_NAME'] ?></td>
                                <td style="text-align:center"><?= $app['FISCAL_YEAR'] ?></td>
                                <td style="text-align:center"><?= number_format($app['AMOUNT']) ?></td>
                                <td style="text-align:center"><?php
                                    if ($app['STATUS'] == 'N')
                                        echo "READY FOR BILL PAYMENT";
                                    else
                                        "FINISHED";
                                    ?></td>
                                <td style="text-align:center"><?= $app['VALID_DATE'] ?></td>
                            </tr>
                            <?php } ?>

                    </tbody>

                </table>
            </div>
        </div>
    </div>


</div>

<script type="text/javascript">

    $(window).on('shown.bs.modal', function () {
        $('#birthday').daterangepicker({
            singleDatePicker: true,
            calender_style: "picker_2"
        }, function (start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
        })
    });


    $(document).ready(function () {
        $('#datatable').dataTable();
        $('#datatable-keytable').DataTable({
            keys: true
        });
        $('#datatable-responsive').DataTable();
        $('#datatable-scroller').DataTable({
            ajax: "js/datatables/json/scroller-demo.json",
            deferRender: true,
            scrollY: 380,
            scrollCollapse: true,
            scroller: true
        });
        var table = $('#datatable-fixed-header').DataTable({
            fixedHeader: true
        });
    });
    TableManageButtons.init();


//    $('form').submit(function (e) {
//        e.preventDefault();
//        var submit = true;
//
//        if (!document.getElementById('method').value) {
//            alert('Enter a Method');
//            submit = false;
//            return false;
//        }
//
//        if (!document.getElementById('p_bill_amt').value) {
//            alert('Enter Bill Amount');
//            submit = false;
//            return false;
//        }
//        alert("HI");
//        //submit = checkvalue(document.getElementById('p_bill_amt').value);
//        if (!submit)
//            return false;
//
//        if (submit) {
//            var stat = confirm("Create a Contract Agreement?");
//            if (stat)
//                this.submit();
//        }
//        return false;
//    });

    function number2text(value) {
        var fraction = Math.round(frac(value) * 100);
        var f_text = "";

        if (fraction > 0) {
            f_text = "AND " + convert_number(fraction) + " POYSA";
        }
        document.getElementById("in_words").value = convert_number(value) + " TAKA " + f_text + " ONLY";
    }


    function frac(f) {
        return f % 1;
    }

    function convert_number(number)
    {
        if ((number < 0) || (number > 999999999))
        {
            return "NUMBER OUT OF RANGE!";
        }
        var Gn = Math.floor(number / 10000000);  /* Crore */
        number -= Gn * 10000000;
        var kn = Math.floor(number / 100000);     /* lakhs */
        number -= kn * 100000;
        var Hn = Math.floor(number / 1000);      /* thousand */
        number -= Hn * 1000;
        var Dn = Math.floor(number / 100);       /* Tens (deca) */
        number = number % 100;               /* Ones */
        var tn = Math.floor(number / 10);
        var one = Math.floor(number % 10);
        var res = "";

        if (Gn > 0)
        {
            res += (convert_number(Gn) + " KOTI");
        }
        if (kn > 0)
        {
            res += (((res == "") ? "" : " ") +
                    convert_number(kn) + " LAKH");
        }
        if (Hn > 0)
        {
            res += (((res == "") ? "" : " ") +
                    convert_number(Hn) + " THOUSAND");
        }

        if (Dn)
        {
            res += (((res == "") ? "" : " ") +
                    convert_number(Dn) + " HUNDRED");
        }


        var ones = Array("", "ONE", "TWO", "THREE", "FOUR", "FIVE", "SIX", "SEVEN", "EIGHT", "NINE", "TEN", "ELEVEN", "TWELVE", "THIRTEEN", "FOURTEEN", "FIFTEEN", "SIXTEEN", "SEVENTEEN", "EIGHTEEN", "NINETEEN");
        var tens = Array("", "", "TWENTY", "THIRTY", "FOURTY", "FIFTY", "SIXTY", "SEVENTY", "EIGHTY", "NINETY");

        if (tn > 0 || one > 0)
        {
            if (!(res == ""))
            {
                res += " AND ";
            }
            if (tn < 2)
            {
                res += ones[tn * 10 + one];
            }
            else
            {

                res += tens[tn];
                if (one > 0)
                {
                    res += ("-" + ones[one]);
                }
            }
        }

        if (res == "")
        {
            res = "zero";
        }
        return res;
    }



</script>



