<div id="mycontainer"  class="row">
    
    <div class="col-md-10 col-sm-10 col-xs-10 col-md-offset-1 col-sm-offset-1 col-xs-offset-1" style="padding-top: 30px" >
        <div class="x_panel">
            <div class="x_title">
                <h2>Create / Update Approval Authority</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <form class="form-horizontal form-label-left" novalidate autocomplete="off" action="<?= $this->baseUrl() ?>/Admin/approveauthmanage" method="post">

                    <input type="hidden" name="p_type_id" value="<?= $this->procdata['USER_TYPE_ID'] ?>">
                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">User Type Name <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input class="form-control col-md-7 col-xs-12" <?php if ($this->procdata['USER_TYPE_NAME']) { ?>value="<?= $this->procdata['USER_TYPE_NAME'] ?>"<?php } ?>  name="p_type" placeholder="Enter User Type Name" required="required" type="text">
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">User Type Status
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select class="select2_single form-control" tabindex="-1" required="required" name="p_type_yn">
                                <option value="Y" <?php if ($this->procdata['ACTIVE_YN'] == 'Y') echo "selected"; ?>>YES</option>
                                <option value="N" <?php if ($this->procdata['ACTIVE_YN'] == 'N') echo "selected"; ?>>NO</option>
                            </select>
                        </div>
                    </div>
                    
                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Approval Authority Status
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select class="select2_single form-control" tabindex="-1" required="required" name="p_auth_yn">
                                <option value="Y" <?php if ($this->procdata['APPROVE_AUTH'] == 'Y') echo "selected"; ?>>YES</option>
                                <option value="N" <?php if ($this->procdata['APPROVE_AUTH'] == 'N') echo "selected"; ?>>NO</option>
                            </select>
                        </div>
                    </div>


                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-3">
                            <a href="index" class="btn btn-primary">Cancel</a>
                            <button  type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
    
    <div class="col-md-10 col-sm-10 col-xs-10 col-md-offset-1 col-sm-offset-1 col-xs-offset-1" >
        <div class="x_panel">
            <div class="x_title">
                <h2>Approval Authority List </h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a href="#"><i class="fa fa-chevron-up"></i></a>
                    </li>

                    <li><a href="#"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>SL#</th>
                            <th>USER TYPE NAME</th>
                            <th>TYPE STATUS</th>
                            <th>APPROVAL AUTHORITY</th>
                            <th>ACTION</th>
                        </tr>
                    </thead>


                    <tbody>
                        <?php
                        $i = 1;
                        foreach ($this->userlist as $user) {
                            ?>
                            <tr>
                                <td><?= $i++; ?></td>
                                <td><?= $user['USER_TYPE_NAME'] ?></td>
                                <td><?php
                                    if ($user['ACTIVE_YN'] == 'Y')
                                        echo 'ENABLE';
                                    else
                                        echo 'DISABLE';
                                    ?></td>
                                <td><?php
                                    if ($user['APPROVE_AUTH'] == 'Y')
                                        echo 'ENABLE';
                                    else
                                        echo 'DISABLE';
                                    ?></td>
                                <td><a href="approveauthmanage?id=<?= $user['USER_TYPE_ID'] ?>" class="btn btn-success">Update</a></td>
<!--                        <form action="updatestaffdata" method="get">
                            <input type="hidden" value="<?= $user['USER_ID'] ?>" name="userid"/>
                            <td><input type="submit" value="Update" class="btn btn-success"/></td>
                        </form>-->
                        </tr>
                    <?php } ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function () {
        $('#datatable').dataTable();
        $('#datatable-keytable').DataTable({
            keys: true
        });
        $('#datatable-responsive').DataTable();
        $('#datatable-scroller').DataTable({
            ajax: "js/datatables/json/scroller-demo.json",
            deferRender: true,
            scrollY: 380,
            scrollCollapse: true,
            scroller: true
        });
        var table = $('#datatable-fixed-header').DataTable({
            fixedHeader: true
        });
    });
    TableManageButtons.init();
</script>





