<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12" style="min-height: 500px">
        <div class="x_panel">
            <div class="x_title">
                <h2>Staff List </h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a href="#"><i class="fa fa-chevron-up"></i></a>
                    </li>

                    <li><a href="#"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>SL#</th>
                            <th>FULL NAME</th>
                            <th>CREATE DATE</th>
                            <th>USER TYPE</th>
                            <th>MOBILE NO.</th>
                            <th>EMAIL</th>
                            <th>STATUS</th>
                            <th>ACTION</th>
                        </tr>
                    </thead>


                    <tbody>
                        <?php
                        $i = 1;
                        foreach ($this->userlist as $user) {
                            ?>
                            <tr>
                                <td><?= $i++; ?></td>
                                <td><?= $user['FULL_NAME'] ?></td>
                                <td><?= $user['CREATE_DATE'] ?></td>
                                <td><?= $user['USER_TYPE_NAME'] ?></td>
                                <td><?= $user['MOBILE'] ?></td>
                                <td><?= $user['EMAIL'] ?></td>
                                <td><?php
                                    if ($user['ACTIVE_YN'] == 'Y')
                                        echo 'ENABLE';
                                    else
                                        'DISABLE';
                                    ?></td>
                                <td><a href="updatestaffdata?userid=<?= $user['USER_ID'] ?>" class="btn btn-success">Update</a></td>
<!--                        <form action="updatestaffdata" method="get">
                            <input type="hidden" value="<?= $user['USER_ID'] ?>" name="userid"/>
                            <td><input type="submit" value="Update" class="btn btn-success"/></td>
                        </form>-->
                        </tr>
                    <?php } ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function () {
        $('#datatable').dataTable();
        $('#datatable-keytable').DataTable({
            keys: true
        });
        $('#datatable-responsive').DataTable();
        $('#datatable-scroller').DataTable({
            ajax: "js/datatables/json/scroller-demo.json",
            deferRender: true,
            scrollY: 380,
            scrollCollapse: true,
            scroller: true
        });
        var table = $('#datatable-fixed-header').DataTable({
            fixedHeader: true
        });
    });
    TableManageButtons.init();
</script>





